name: doacaosangue_container
services:
  nwe.doacaosangue.api:
    image: ${DOCKER_REGISTRY-}nwedoacaosangueapi
    build:
      context: .
      dockerfile: src/NWE.DoacaoSangue.API/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - '1433:1433'    
    expose:
      - 1433